name: linter check
on: 
  - push
  - pull_request
jobs:
  linting:
    runs-on: ubuntu-latest
    steps: 
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: make install
      - run: make lint
      - run: make test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
